require('dotenv').config();

module.exports = {
    PORT: parseInt(process.env.PORT || '7000', 10),
    DEBUG: (process.env.DEBUG_MODE || '').toLowerCase() === 'true',
    CACHE_ENABLED: (process.env.CACHE_ENABLED || 'true').toLowerCase() !== 'false',
    CACHE_TTL_MS: parseInt(process.env.CACHE_TTL_MS || '21600000', 10),
    MAX_CACHE_ENTRIES: parseInt(process.env.MAX_CACHE_ENTRIES || '300', 10),
    PREFETCH_ENABLED: (process.env.PREFETCH_ENABLED || 'true').toLowerCase() !== 'false',
    PREFETCH_MAX_BYTES: parseInt(process.env.PREFETCH_MAX_BYTES || '150000000', 10),
    ADDON_NAME: process.env.ADDON_NAME || 'IPTV Stremio Addon',
    ADDON_DESCRIPTION: process.env.ADDON_DESCRIPTION || 'Stream your IPTV channels in Stremio',
    ADDON_LOGO_URL: process.env.ADDON_LOGO_URL || 'https://i.imgur.com/vN5tLuv.jpeg',
    LOGO_CACHE_ENABLED: (process.env.LOGO_CACHE_ENABLED || 'true').toLowerCase() !== 'false',
    CONFIG_SECRET: process.env.CONFIG_SECRET || null,
    IP_RATE_LIMIT_ENABLED: (process.env.IP_RATE_LIMIT_ENABLED || 'true').toLowerCase() !== 'false',
    IP_RATE_LIMIT_WINDOW_MS: parseInt(process.env.IP_RATE_LIMIT_WINDOW_MS || '300000', 10),
    IP_RATE_LIMIT_MAX: parseInt(process.env.IP_RATE_LIMIT_MAX || '300', 10),
    TOKEN_RATE_LIMIT_ENABLED: (process.env.TOKEN_RATE_LIMIT_ENABLED || 'true').toLowerCase() !== 'false',
    TOKEN_RATE_LIMIT_WINDOW_MS: parseInt(process.env.TOKEN_RATE_LIMIT_WINDOW_MS || '60000', 10),
    TOKEN_RATE_LIMIT_MAX: parseInt(process.env.TOKEN_RATE_LIMIT_MAX || '60', 10),
    SQLITE_PATH: process.env.SQLITE_PATH || null,
    SQLITE_GC_INTERVAL_MS: parseInt(process.env.SQLITE_GC_INTERVAL_MS || '21600000', 10),
    SQLITE_VACUUM_INTERVAL_MS: parseInt(process.env.SQLITE_VACUUM_INTERVAL_MS || '604800000', 10),
    IPTV_ORG_CACHE_TTL_MS: parseInt(process.env.IPTV_ORG_CACHE_TTL_MS || '') || 21600000,
};
